warning_threshold: 5

force_cast:
  severity: warning

force_try:
  severity: warning

empty_count:
  severity: warning

cyclomatic_complexity:
  warning: 100
  error: 90

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 400
  error: 2010

type_body_length:
  warning: 200
  error: 920

function_body_length:
  warning: 40
  error: 241

line_length:
  warning: 400
  error: 1000
  ignores_comments: true
  ignores_function_declarations: true

type_name:
  excluded:
    - T

identifier_name:
  allowed_symbols:
    - _
  min_length:
    error: 0
    warning: 2
  max_length:
    warning: 50
  validates_start_with_lowercase: false
  excluded:
    - x
    - y
    - i

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - array_init
  - closure_end_indentation
  - contains_over_first_not_nil
  - explicit_init
  - multiline_parameters
  - object_literal
  - overridden_super_call
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - Pods
  - Desafio-PicPay-RicardoTests
  - Desafio-PicPay-RicardoUITests
  - R.generated.swift
